name: Deploy Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/**'

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies and package Lambda
        run: |
          cd lambda
          pip install -r requirements.txt -t .
          zip -r package.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name TanaMonitoringFunction \
            --zip-file fileb://lambda/package.zip
